server:
  servlet:
    context-path: /api
spring:
  liquibase:
    change-log: classpath*:migrations/master-changelog.yml
    user: doctor
    url: jdbc:postgresql://localhost:5432/doctor_map_app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/doctor_map_app
    username: doctor
    password: doctor
mybatis:
  configuration:
    map-underscore-to-camel-case: true
nominatim:
  url:
    search: https://nominatim.openstreetmap.org/search/
    start-param: ?format=geojson&limit=1

#logging:
#  level:
#    org:
#      springframework: WARN
#    ru:
#      vsu:
#        cs:
#          app:
#            db:
#              repositories:
#                SickRepository: DEBUG
